%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook:
%    S:\Hedrich\Studenten\Krueger\Zwischenspeicher\Messung_Viskosität_Öl_hedrich\SHELL\Viskosität_SHELL.xlsx
%    Worksheet: Tabelle1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2017/08/03 16:06:47

%% Import the data, extracting spreadsheet dates in MATLAB serial date number format (datenum)
[~, ~, raw, dateNums] = xlsread('S:\Hedrich\Studenten\Krueger\Zwischenspeicher\Messung_Viskosität_Öl_hedrich\SHELL\Viskosität_SHELL.xlsx','Tabelle1','A2:S13','',@convertSpreadsheetDates);
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
cellVectors = raw(:,[2,3,4]);
raw = raw(:,[1,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]);
dateNums = dateNums(:,[1,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]);

%% Replace date strings by MATLAB serial date numbers (datenum)
R = ~cellfun(@isequalwithequalnans,dateNums,raw) & cellfun('isclass',raw,'char'); % Find spreadsheet dates
raw(R) = dateNums(R);

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
Datum = data(:,1);
Fluessigkeit = cellVectors(:,1);
LfdNr = cellVectors(:,2);
Kapillare = cellVectors(:,3);
Kapillarkonstante = data(:,2);
TempC = data(:,3);
K = data(:,4);
systemFehlerTemp = data(:,5);
AbweichungTemp = data(:,6);
kinematischeViskositaetmm = data(:,7);
Standardabweichnungkinema = data(:,8);
Hagenbachkorrekturs = data(:,9);
Messzeit1s = data(:,10);
Messzeit2s = data(:,11);
Messzeit3s = data(:,12);
MittelwertMesszeits = data(:,13);
korrigierterMittelwerts = data(:,14);
kinematischeViskositaet_b = data(:,15);
AbweichungViskosittmms = data(:,16);

%% Clear temporary variables
clearvars data raw dateNums cellVectors R;

%%Bennenung Variablen
x=K.^-1; %x als Temperatur 1/K
y=log(kinematischeViskositaetmm); %y als logarithmus der kin. Viskositaet
sd=Standardabweichnungkinema; %sd ist die Standardabweichung

%%Regression
mdl = LinearModel.fit(x,y)

%%Plots
errorbar(x,y,sd,'o')
xlabel('1/Temperatur [1/K]')
ylabel('kinematische Viskosität [mm²/s]')
