from pathlib import Path

from rdflib import Namespace, Literal
from rdflib.namespace import DCAT, DCMITYPE, DCTERMS, RDF, RDFS, XSD, SSN, SDO, FOAF
from pyKRAKEN.kraken import (
    DBO,
    QUDT,
    UNIT,
    QUANTITYKIND,
    Kraken
)

import gitlab_db_mdgen


# this should ideally be something like e.g.:
# https://fst.tu-darmstadt.de/namespaces/components/id/
# or w3id
# which redirects to e.g.
# https://fst.tu-darmstadt.de/namespaces/components/doc/
# which redirects to a webserver with static html generated by this, or just directly to
# ns_root = "https://git.rwth-aachen.de/fst-tuda/projects/rdm/datasheets-mockup/"
# FST = Namespace(ns_root + "-/blob/main/")
# COMPONENT = Namespace(FST["component/"])
# SUBSTANCE = Namespace(FST["substance/"])

SCHEMA = Namespace("https://schema.org/")
SSN_SYSTEM = Namespace("https://www.w3.org/ns/ssn/systems/")

COMPONENT = Namespace("https://w3id.org/fst/resource/")
SUBSTANCE = Namespace("https://w3id.org/fst/resource/")

def main():
    data = Kraken(base=COMPONENT)
    # data.g.bind("fst-component", COMPONENT)
    # data.g.bind("fst-substance", SUBSTANCE)
    data.g.bind("fst", COMPONENT)

    gas_cylinder_id = "018bb4b1-db4a-7bbd-a299-ee3b49b5d7f5"  # str(uuid6())

    # the component = the accumulator testrig
    gas_cylinder = COMPONENT[gas_cylinder_id]
   
    data.g.add((gas_cylinder, RDF.type, DCMITYPE.PhysicalObject))
    
    data.g.add((gas_cylinder, RDFS.label, Literal("accumulator testrig")))
    data.g.add((gas_cylinder, DCTERMS.identifier, Literal(gas_cylinder_id)))
    # data.g.add((gas_cylinder, DCTERMS.identifier, Literal("")))
    data.g.add((gas_cylinder, DBO.owner, Literal("Chair of Fluidsystems")))
    data.g.add((gas_cylinder, SDO.manufacturer, Literal("Chair of Fluidsystems")))
    # data.g.add((gas_cylinder, SDO.serialNumber, Literal("")))

    # properties
    displacement_area = COMPONENT[gas_cylinder_id + "/A_d"]
    data.g.add((gas_cylinder, SSN.hasProperty, displacement_area))
    data.g.add((displacement_area, RDF.type, SSN.Property))
    data.g.add((displacement_area, RDF.type, QUDT.Quantity))
    data.g.add((displacement_area, RDFS.label, Literal("displacement area")))
    data.g.add((displacement_area, QUDT.symbol, Literal("A_d")))
    data.g.add((displacement_area, QUDT.hasQuantityKind, QUANTITYKIND.Area))
    data.g.add((displacement_area, QUDT.unit, UNIT.M2))
    data.g.add((displacement_area, SCHEMA.value, Literal("-0.001963495408494", datatype=XSD.double)))
    data.g.add((displacement_area, RDFS.comment, Literal("negative direction")))
    # TODO: There might be sophisticated special data types for uncertainties in the future 12.2023
    data.g.add((displacement_area, SSN_SYSTEM.Accuracy, Literal("1.57111048605989e-06", datatype=XSD.double)))
    data.g.add((displacement_area, RDFS.comment, Literal("(manufacturing)-accuracy of the cylinder diameter (50mm) estimated as 0.02mm by Mr. Rexer from which the accuracy of the displacement area is calculated. 12.2023")))

    ## NOTE: The used oil will get its own substance data set and the dataset will be linked inside matlab inside the
    # measurement data as used test rig.

    # documentation this can probably be automated
    img = COMPONENT[gas_cylinder_id + "/img/IMG_accumulator_testrig_mounted_in_hydropulser.jpg"]
    data.g.add((gas_cylinder, SDO.subjectOf, img))
    data.g.add((gas_cylinder, SDO.image, img))

    docs = COMPONENT[gas_cylinder_id + "/CAD"]
    data.g.add((gas_cylinder, SDO.subjectOf, docs))
    data.g.add((gas_cylinder, SDO.documentation, docs))

    thesis = COMPONENT[gas_cylinder_id + "/doc/report_181117_S330_Masterarbeit_Modellierung_und_experimentelle_Untersuchung_eines_hydropneumatischen_Federbeins_mit_Schaumspeicher_Rexer.pdf"]
    data.g.add((gas_cylinder, SDO.subjectOf, thesis))
    data.g.add((gas_cylinder, SDO.documentation, thesis))

    datasheet = COMPONENT[gas_cylinder_id + "/doc/BG_Speicherpruefstand.pdf"]
    data.g.add((gas_cylinder, SDO.subjectOf, datasheet))
    data.g.add((gas_cylinder, SDO.documentation, datasheet))

    # rdf doc references
    docttl = COMPONENT[gas_cylinder_id + "/rdf.ttl"]
    data.g.add((docttl, RDF.type, FOAF.Document))
    data.g.add((docttl, FOAF.primaryTopic, gas_cylinder))

    docxml = COMPONENT[gas_cylinder_id + "/rdf.xml"]
    data.g.add((docxml, RDF.type, FOAF.Document))
    data.g.add((docxml, FOAF.primaryTopic, gas_cylinder))

    docjson = COMPONENT[gas_cylinder_id + "/rdf.json"]
    data.g.add((docjson, RDF.type, FOAF.Document))
    data.g.add((docjson, FOAF.primaryTopic, gas_cylinder))


    current_python_file_dir_path = Path(__file__).parent.resolve()
    dir_path = Path(f"{current_python_file_dir_path}/{gas_cylinder_id}")

    try:
        dir_path.mkdir()
    except FileExistsError:
        pass

    file_path = f"{dir_path}/rdf"
    print(data.g.serialize(destination=f"{file_path}.json", format="json-ld", auto_compact=True))
    print(data.g.serialize(destination=f"{file_path}.ttl", format="longturtle", encoding="utf-8"))
    print(data.g.serialize(destination=f"{file_path}.xml", format="xml"))

    gitlab_db_mdgen.generate_sensor_md(f'{dir_path}/')

if __name__ == '__main__':
    main()
