%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook:
%    C:\Users\Administrator\Desktop\Messung_Dichte_Öl_Hedrich\SHELL\Dichte_SHELL.xlsx
%    Worksheet: Tabelle1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2017/08/16 15:25:04

%% Import the data, extracting spreadsheet dates in MATLAB serial date number format (datenum)
[~, ~, raw, dateNums] = xlsread('\\FST\Studierende\N.Broetz\Studenten\Rexer\21_Speicherprüfstand\Messung_Viskosität&Dichte_Öl_hedrich\Shell\SHELL_Dichte\Dichte_SHELL.xlsx','Tabelle1','A2:L12','',@convertSpreadsheetDates);
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
cellVectors = raw(:,2);
raw = raw(:,[1,3,4,5,6,7,8,9,10,11,12]);
dateNums = dateNums(:,[1,3,4,5,6,7,8,9,10,11,12]);

%% Replace date strings by MATLAB serial date numbers (datenum)
R = ~cellfun(@isequalwithequalnans,dateNums,raw) & cellfun('isclass',raw,'char'); % Find spreadsheet dates
raw(R) = dateNums(R);

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
Datum1 = data(:,1);
Fluessigkeit1 = cellVectors(:,1);
LfdNr1 = data(:,2);
TempC1 = data(:,3);
K1 = data(:,4);
systemFehlerTemp1 = data(:,5);
AbweichungTemp1 = data(:,6);
Dichte = data(:,7);
StandardabweichnungDichte1 = data(:,8);
Messzeits1 = data(:,9);
VarName1 = data(:,10);
lnDichte1 = data(:,11);

%% Clear temporary variables
clearvars data raw dateNums cellVectors R;

%%Bennenung Variablen
t=K1; %t als Temperatur K
y=Dichte; %y als logarithmus der Dichte
sd=StandardabweichnungDichte1; %sd ist die Standardabweichung der Dichte

%%Regression
mdl = LinearModel.fit(t,y)

%%Plots
errorbar(t,y,sd,'o')
xlabel('TEMPERATUR \tau in K')
ylabel('DICHTE \rho in kg/m³')
title('Dichte SHELL TELUS S2 M')
hold on;
plot(289.25,879,'xr');
text(292.25,879,'\leftarrow Datenblattangabe','Color', 'r');
